[package]
name = "route-search"
version = "0.1.0"
authors = ["djade <djadenkus@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
itertools = "0.7.8"
log = "0.4.3"
simplelog = "0.5.2"
